# -*- coding: utf-8 -*-
"""cedulas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pdBZsqPgMT5hCbDkPyvDrOyVJ_rRw2pZ
"""

numero = int(input("Digite um número "))

cedula100 = numero//100
numero = numero % 100

cedula50 = numero//50
numero = numero % 50

cedula20 = numero//20
numero = numero % 20

cedula10 = numero//10
numero = numero % 10

cedula5 = numero//5
numero = numero % 5

cedula2 = numero//2
numero = numero % 2

cedula1 = numero//1
numero = numero % 1

print("Você precisará de " )
print(cedula100, "cédula(s) de R$ 100,00")
print(cedula50, "cédula(s) de R$ 50,00")
print(cedula20, "cédula(s) de R$ 20,00")
print(cedula10, "cédula(s) de R$ 10,00")
print(cedula5,"cédula(s) de R$ 5,00")
print(cedula2, "cédula(s) de R$ 2,00")
print(cedula1, "cédula(s) de R$ 1,00")