# -*- coding: utf-8 -*-
"""conversao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pdBZsqPgMT5hCbDkPyvDrOyVJ_rRw2pZ
"""

seg = int(input("Digite o tempo em segundos: "))

h = seg //3600
min = (seg % 3600) // 60
seg_restante = seg % 60

print (f"Isso daria {h:02d}:{min:02d}:{seg_restante:02d}")