# -*- coding: utf-8 -*-
"""formulas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pdBZsqPgMT5hCbDkPyvDrOyVJ_rRw2pZ
"""

a = int(input("Digite o valor de A "))
b = int(input("Digite o valor de B "))
while b <0:
  b = int(input("Valor inválido. Você precisa digitar um número maior ou igual a 0 para B. "))

x = float(input("Digite o valor de X "))
y = float(input("Digite o valor de Y "))

while x==y:
  y = float(input("O valor de Y não pode ser o mesmo de X. Por favor digite outro número. "))

calculo = a + b**x - b**0.5 + (a+b) / (x-y)
print("O valor da expressão é %.2f" %calculo)