# -*- coding: utf-8 -*-
"""manhattan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pdBZsqPgMT5hCbDkPyvDrOyVJ_rRw2pZ
"""

x1 = float(input("Digite o valor de X1 "))
y1 = float(input("Digite o valor de Y1 "))
x2 = float(input("Digite o valor de X2 "))
y2 = float(input("Digite o valor de Y2 "))

distancia = abs(x1-x2)+ abs(y1-y2)

print("O valor da distância é de %.4f" %distancia)