# -*- coding: utf-8 -*-
"""Paralelepipedo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pdBZsqPgMT5hCbDkPyvDrOyVJ_rRw2pZ
"""

A = int(input("Digite o valor de A "))
B = int(input("Digite o valor de B "))
C = int(input("Digite o valor de C "))
V = A*B*C
D = ((A**2) + (B**2) + (C**2))**0.5
print("O volume é igual a %.2f" %V)
print("A diagonal é igual a %.2f" %D)