# -*- coding: utf-8 -*-
"""parcelamento.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pdBZsqPgMT5hCbDkPyvDrOyVJ_rRw2pZ
"""

venda = float(input("Digite o valor da Venda (em R$) "))
while venda<=0:
  venda = float(input("O valor da Venda não pode ser menor ou igual a 0. Por favor digite outro número."))

parcelas = int(input("Digite o número total de Parcelas "))
while parcelas <=0:
  parcelas = int(input("O número de parcelas não pode ser menor ou igual a 0. Por favor digite outro número. "))

cada_parcela = venda/parcelas

print("O valor de cada parcela é de R$ %.2f" %cada_parcela)