# -*- coding: utf-8 -*-
"""salariobonus.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pdBZsqPgMT5hCbDkPyvDrOyVJ_rRw2pZ
"""

nome = (input("Digite o nome do vendedor "))

salario = float(input("Digite o salário fixo do vendedor (em R$) "))
while salario<=0:
  salario = float(input("O salário fixo não pode ser igual ou menor que 0. Por favor digite outro valor. "))

vendas = float(input("Digite o valor total das vendas efetuadas pelo vendedor (em R$) "))
while vendas<0:
  salario = float(input("O salário fixo não pode ser menor que 0. Por favor digite outro valor. "))

comissao = float(input("Digite o valor da porcentagem de comissão sobre as vendas efetuadas. "))

total = salario+(vendas*comissao/100)


print("O valor total que o funcionário deve receber é de %.2f" %total)